# Development Tools
brew "awscli"
brew "colima"
brew "docker"
brew "gnupg"
brew "nvm"
brew "lazygit"
brew "terraform"
brew "neovim"

# Terminal Tools (for zsh configuration)
brew "bat"
brew "fzf"
brew "thefuck"

# Applications
cask "1password"
cask "cursor"
cask "google-chrome"
cask "iterm2"
cask "rectangle"
cask "spotify"
